#!/bin/sh
# postinst script for test
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

EQ3_FW_VERSION="2.7.17"
ROOT_PATH="/var/lib/lxccu/"
logdebug () {
	#echo "Debug: $1 $2"
	return
}
#QUIET=""
QUIET="--quiet"

logsystem() {
    cpuinfo_file="/proc/cpuinfo"
    issue_file="/etc/issue"
    debian_version_file="/etc/debian_version"
    timezone_file="/etc/timezone"
    rpi_issue_file="/etc/rpi-issue"
    fstab_file="/etc/fstab"
    apt_sources_file="/etc/apt/sources.list"

    uname=`uname -a`
    lxc_version=`lxc-version| sed -e 's/lxc version/lxc_version/g'`
    lxc_package=`dpkg -l|grep lxc`

    lxc_check_config=`lxc-checkconfig | head -n 23 | grep -v "\-" | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" | sed -e 's/:/_/g' | tr '\n' '#'`
    deviceinfo=""
    if [ -e "$cpuinfo_file" ]; then
        tmp=`cat $cpuinfo_file | sed -e 's/:/_/g' | tr '\n' '#'`
        deviceinfo="device: $tmp |"
    fi
    deviceinfo="$deviceinfo lxcconfig: $lxc_check_config |"
    if [ -e "$fstab_file" ]; then
        fstab_file=`cat $fstab_file | grep -v "#" | tr '\n' '#'`
        deviceinfo="$deviceinfo fstab_file: $fstab_file|"
    fi
    if [ -e "$issue_file" ]; then
        issue=`cat $issue_file | sed -e 's/:/,/g'`
        deviceinfo="$deviceinfo os: $issue|"
    fi
    if [ -e "$debian_version_file" ]; then
        debian_version=`cat $debian_version_file`
        deviceinfo="$deviceinfo debian_version: $debian_version|"
    fi
    if [ -e "$timezone_file" ]; then
        timezone=`cat $timezone_file`
        deviceinfo="$deviceinfo timezone: $timezone|"
    fi
    if [ -e "$rpi_issue_file" ]; then
        rpi_issue=`cat $rpi_issue_file | sed -e 's/:/,/g'`
        deviceinfo="$deviceinfo rpi_issue: $rpi_issue|"
    fi

    if [ -e "$apt_sources_file" ]; then
        sources_list=`cat $apt_sources_file | sed -e 's/:/,/g' | grep -v "#" | tr '\n' '#'`
        deviceinfo="$deviceinfo sources_list: $sources_list|"
    fi
    deviceinfo="$deviceinfo $lxc_version|"
    deviceinfo="$deviceinfo lxc_package: $lxc_package|"

    deviceinfo="$deviceinfo $uname"

    url="http://api.536514f44cbecf864f000008.boweryapps.com/betatest/addinstallation"

    echo "The following data will be logged"
    echo "==========================================="
    echo $deviceinfo
    echo "==========================================="
    wget --quiet --post-data="information=$deviceinfo" $url -O /dev/null  
}

case "$1" in
    configure)
		logsystem

		# download fw
		EQ3_FW_URL="http://www.eq-3.de/Downloads/Software/HM-CCU2-Firmware_Updates/HM-CCU2-${EQ3_FW_VERSION}/HM-CCU2-${EQ3_FW_VERSION}.tar.gz"
		logdebug "EQ3_FW_URL" $EQ3_FW_URL
		EQ3_FW="/opt/HM-CCU2-${EQ3_FW_VERSION}.tar.gz"
		logdebug "EQ3_FW" $EQ3_FW
		echo "Downloading firmware"
		wget "$EQ3_FW_URL" $QUIET --output-document="$EQ3_FW"
		if [ ! -f "$EQ3_FW" ]; then
			echo "Can not download firmware. Are you connected to the internet?"
			exit 1
		fi


		# extract fw
		LXCCU_ROOT="/opt/lxccu/"
		logdebug "LXCCU_ROOT" $LXCCU_ROOT
		mkdir -p $LXCCU_ROOT
		LXCCU_ROOTFS="/opt/lxccu/root"
		logdebug "LXCCU_ROOTFS" $LXCCU_ROOTFS
		echo "Extracting firmware"
		tar xzf $EQ3_FW -C /opt/


		# extract ubi image
		echo "Extract ubi image"
		LOG=`mktemp`
		/var/lib/ubi_reader/ubi_extract_files.py -q -k -o $LXCCU_ROOT --log-file $LOG /opt/rootfs.ubi

		# clean up download sources
		echo "Remove downloaded files"
		rm -f $EQ3_FW
		rm -f /opt/EULA.de
		rm -f /opt/EULA.en
		rm -f /opt/rootfs.ubi
		rm -f /opt/uImage
		rm -f /opt/update_script


		# patch fw
		cd $LXCCU_ROOTFS 
		echo "apply patch"
		patch $QUIET --input "${ROOT_PATH}source/patches/lxccu-${EQ3_FW_VERSION}.patch" -p1


		# apply scripts
		cd $LXCCU_ROOTFS 
		echo "apply script"
		sh "${ROOT_PATH}source/scripts/lxccu-${EQ3_FW_VERSION}.sh"


		# sdcard
		echo "create sd card"
		mkdir -p /media/sd-lxccu/
		touch /media/sd-lxccu/.initialised


		# lxc config file
		echo "create lxc config file"
		cat <<EOF > /opt/lxccu/config
lxc.mount.entry = proc proc proc nodev,noexec,nosuid 0 0
lxc.mount.entry = sysfs sys sysfs defaults  0 0
lxc.mount.entry = varfs var tmpfs defaults,size=196M 0 0
#lxc.mount.entry = devpts dev/pts devpts nosuid,mode=0620,ptmxmode=000,newinstance 0 0
lxc.mount.entry = devpts dev/pts devpts defaults,newinstance 0 0
lxc.mount.entry = /media/sd-lxccu  media/sd-mmcblk0/ none defaults,bind 0 0

lxc.tty = 1
lxc.pts = 1
lxc.cgroup.devices.deny = a

# /dev/null and zero
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm

# consoles
lxc.cgroup.devices.allow = c 5:1 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
lxc.cgroup.devices.allow = c 4:0 rwm
lxc.cgroup.devices.allow = c 4:1 rwm

# /dev/{,u}random
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 1:8 rwm

# /dev/pts/* - pts namespaces are "coming soon"
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 5:2 rwm

#lxc.cgroup.devices.allow = c 136:* rwm # pts
#lxc.cgroup.devices.allow = c 254:0 rwm # rtc
#lxc.cgroup.devices.allow = c 5:* rwm
#lxc.cgroup.devices.allow = c 4:* rwm # ttyXX
#lxc.cgroup.devices.allow = c 1:* rwm
#lxc.cgroup.devices.allow = b 7:* rwm # loop
#lxc.cgroup.devices.allow = b 1:* rwm # ram

lxc.utsname = lxccu
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxccubr0
lxc.network.hwaddr = 4a:49:43:49:79:bf
lxc.rootfs = /opt/lxccu/root
EOF
		
		# add container
		echo "create lxc container lxccu"
		lxc-create -n lxccu -f "/opt/lxccu/config"
		retval=$?

		if [ $retval -ne 0 ]; then
			lxc-create -n lxccu -f "/opt/lxccu/config" -t none
		fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
