#!/bin/bash

EQ3_FW_VERSION="2.13.7"
EQ3_FW_MD5SUM="95ffda9e6d94b979562b782abb5d9d74"

ROOT_PATH="/var/lib/lxccu/"
LXCCU_ROOT="/var/lib/lxc/lxccu/"
LXCCU_ROOTFS="/var/lib/lxc/lxccu/root"
CONTAINER_NAME="lxccu"
LXC_AUTOSTART="/etc/lxc/auto/lxccu"
logdebug () {
	#echo "Debug: $1 $2"
	return
}
#QUIET=""
QUIET="--quiet"


stop_lxccu() {

    CONTAINER_EXITS=$(lxc-ls | grep $CONTAINER_NAME | wc -l)
    if [ $CONTAINER_EXITS -ne 0 ]; then
        if lxc-info -n "$CONTAINER_NAME" | grep -qs "RUNNING"
        then
            echo "shutdown $CONTAINER_NAME"
            # @TODO when there is a rootfs symlink -> change to shutdown but test it
            lxc-stop -n "$CONTAINER_NAME"  
    #2>&1 > /dev/null
            echo -n "waiting for $CONTAINER_NAME shutdown"
            timeout=30
            while [ $timeout -gt 0 ]
            do
                echo -n "."
                timeout=$(($timeout-1));sleep 1
                if lxc-info -n "$CONTAINER_NAME"| grep -qs "STOPPED"
                then
                    timeout=0
                fi
            done
            echo ""
            echo "$CONTAINER_NAME shutdown complete"
        fi
    fi	
}

remove_lxccu () {
	stop_lxccu
	
    CONTAINER_EXITS=$(lxc-ls | grep $CONTAINER_NAME | wc -l)
    if [ $CONTAINER_EXITS -ne 0 ]; then
        lxc-destroy -n "$CONTAINER_NAME"
    fi
    echo "remove files"
    if [ -f "$LXC_AUTOSTART" ]; then
        unlink "$LXC_AUTOSTART"
    fi
    if [ -d "$LXCCU_ROOT" ]; then
        rm -rf $LXCCU_ROOT
    fi

}

restore_lxccu_backup () {
	echo "restore"
	cd /var/lib/lxc/lxccu/root
	tar xzf /opt/lxccu_backup.tar.gz
	lastoctet_macaddress=`grep '^ *lxc\.network\.hwaddr *=' /opt/lxccu_config_backup | cut -d':' -f6`
	echo "remove install backup"
	rm /opt/lxccu_config_backup
	rm /opt/lxccu_backup.tar.gz
}


# get_bridge_name() {
# 	local bridgename=""
# 	bridgename=$(brctl show | awk 'NR % 2 == 0' | awk '{print $1}' | grep -v lxccubr0 )
# 	#count=$(brctl show | awk 'NR % 2 == 0' | awk '{print $1}' | wc -l)
# 	if [ -z "$bridgename" ]; then
# 		echo "lxccubr0"
# 	else
# 		echo "$bridgename"
# 	fi
# }



